### ISSUE TITLE
exe indicates starting, then does nothing

### ISSUE THREAD

**Issue by Abadima** [NotII/Tidal-RPC#19]
the title says it

**Comment by NotII** [comment]
ill take a look into it!

**Comment by NotII** [comment]
May I ask is there any errors at all?

**Comment by Abadima** [comment]
nope, it just simply closes

**Comment by Abadima** [comment]
Just reinstalled it, have a look: 
https://gyazo.com/5df91d8bbe5e63220234d4b5552d8b29
https://gyazo.com/5df91d8bbe5e63220234d4b5552d8b29

**Comment by NotII** [comment]
Should be launching the Tidal-RPC.exe file, thats for getting processes info to get the data from tidal

**Comment by Abadima** [comment]
I've done that even after the files were loaded, just the same thing again, so I figured maybe the other exe file would do something

**Comment by NotII** [comment]
Would you be able to show a video thanks

**Comment by Abadima** [comment]
AHA, CAUGHT AN ERROR!

Starting...

(node:2928) UnhandledPromiseRejectionWarning: Error: RPC_CONNECTION_TIMEOUT
    at Timeout._onTimeout (C:\Users\owner\Downloads\Tidal-RPC-main\Tidal-RPC-main\node_modules\discord-rpc\src\client.js:100:47)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `Tidal-RPC --trace-warnings ...` to show where the warning was created)
(node:2928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NotII** [comment]
Ill take a look and see if I can find the cause of the error, seems to be a issue with the RPC connecting to the discord client

**Comment by Abadima** [comment]
Stable 94542 (e0f6b92) Host 1.0.9002 Windows 10 64-Bit (10.0.19043)

if it helps, here's the stats

**Comment by NotII** [comment]
Found the issue going to deploy a fix

**Comment by Abadima** [comment]
oki

**Comment by NotII** [comment]
https://github.com/NotII/Tidal-RPC/releases/tag/v1.2 should fix the issue

**Comment by Abadima** [comment]
I’ll have a try

**Comment by NotII** [comment]
Let me know how it goes

**Comment by Abadima** [comment]
Everything Works! I'll reopen if I encounter any new problems
